### ISSUE TITLE
alpine-x86/files/0000000000005515 is 404

### ISSUE THREAD

**Issue by guest271314** [cemalgnlts/now#1]
![Screenshot_2023-07-03_21-01-05](https://github.com/cemalgnlts/now/assets/4174848/6250f9e8-d30e-4339-a6aa-d0b2d348ae74)

**Comment by cemalgnlts** [comment]
Hi,

There are only node packages to get a small release. It probably wants a file but it's not included so it's a problem, but it's not a big deal.

This project is not very stable. The project uses the alpine linux emulator: https://bellard.org/jslinux/ it takes about ~14 seconds to start the node.

I can get it down to ~10 seconds with a custom linux version in copy/v86, but I can't release it completely because of project issues.

https://github.com/ktock/container2wasm another alternative, but it has a performance problem for about ~16 seconds.

Obviously I am looking for alternatives for performance reasons.

**Comment by guest271314** [comment]
I am just notifying you of the 404 error. My use case for this technology is not to create a GUI, rather just to use a specific program in WASM environment. FYI because I think this project is interesting, and open source, unlike the claims of StackBlitz re running Node.js in the browser - on StackBlitz's Web site, I posted a link to your work on Reddit here https://www.reddit.com/r/node/comments/14q4ah9/node_on_web_use_nodejs_freely_in_your_browser/ and here https://www.reddit.com/r/learnjavascript/comments/14q4azv/node_on_web_use_nodejs_freely_in_your_browser/ so folks who are interested in Node.js in the browser can contribute if they want.

**Comment by cemalgnlts** [comment]
This is great thanks.

I'm sure it will be better if it attracts the attention of the right people.

**Comment by guest271314** [comment]
> This is great thanks.
>
> I'm sure it will be better if it attracts the attention of the right people.

That's questionable and te to be determined. I just found your efforts in this matter worth taking note of. Particularly after this ["... run Node.js, entirely inside your browser"](https://github.com/stackblitz/webcontainer-core/issues/658).
